services:
  database:
    image: postgres:15.3-alpine3.18
    container_name: attempt-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
  api:
    container_name: attempt-api
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/home/attempt
      - ./src/migrations:/home/attempt/src/migrations
    depends_on:
      - database
    env_file:
      - .env
    links:
      - database
volumes:
  database:
    driver: local
